apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    name: pod-backend
  type: LoadBalancer
  ports:
  - name: "backend"
    protocol: "TCP"
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain           # Service name for DNS
spec:
  selector:
    name: pod-backend       # This needs to match the pod's 'name' label
  ports:
    - name: blockchain
      protocol: TCP
      port: 8545            # Port exposed to cluster
      targetPort: 8545