apiVersion: v1
kind: ConfigMap
metadata:
  name: kafkaml-configmap
data:
  # brokers: 192.168.43.7:32001
  control.topic: KAFKA_ML_CONTROL_TOPIC
  
  federated.modelloggertopic: FEDERATED_MODEL_CONTROL_TOPIC

  frontend.url: http://frontend
  backend.url: http://backend:8000
  backend.address: backend:8000 # TODO replace this
  backend.allowedhosts: 127.0.0.1,localhost,backend
  blockchain.address: blockchain:8545
  blockchain.allowedhosts: 127.0.0.1,localhost,blockchain
  tfexecutor.url: http://tfexecutor:8001/
  pthexecutor.url: http://pthexecutor:8002/

  brokers: http://kafka:9092

  # tensorflow.training.image: ertis/kafka-ml-tensorflow_model_training:master
  # tensorflow.inference.image: ertis/kafka-ml-tensorflow_model_inference:master
  # pytorch.training.image: ertis/kafka-ml-pytorch_model_training:master
  # pytorch.inference.image: ertis/kafka-ml-pytorch_model_inference:master

  # debug: "0"

  # BlockChain-based Federated Learning Configuration
  fedml.blockchain.enable: "1"
  fedml.blockchain.rpc-url: http://blockchain.kafkaml:8545
  fedml.blockchain.rpc.localhost-url: http://localhost:8545
  fedml.blockchain.chain-id: "31337"
  fedml.blockchain.network-id: "1999"
  fedml.blockchain.wallet-address: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  fedml.blockchain.wallet-key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
  fedml.blockchain.blockscout-link: "0"
  fedml.blockchain.blockscout-url: http://blockscout:8000
  fedml.blockchain.token-name: KafkaML-FedToken
  fedml.blockchain.token-symbol: KFKMLA
