resources:
  - resources/namespace.yaml
  - resources/kafka-deployment.yaml
  - resources/kafka-service.yaml
  - "../base"

namespace: kafkaml

configMapGenerator:
  - name: federated-kafkaml-configmap
    behavior: merge
    literals:
      - kml.cloud.brokers=kafka:9092
      - federated.data.brokers=kafka:9092
      - federated.data.control.topic=FEDERATED_DATA_CONTROL_TOPIC
      - federated.model.control.topic=FEDERATED_MODEL_CONTROL_TOPIC
      - backend.url=http://federated-backend:8085
      - backend.allowedhosts=127.0.0.1,localhost,federated-backend
      - federated.tensorflow.training.image=host.docker.internal:50000/federated_model_training_tensorflow:latest
      - federated.pytorch.training.image=host.docker.internal:50000/federated_model_training_tensorflow:latest

images:
  - name: kafka
    newName: docker.io/bitnami/kafka
    newTag: "3.4.0-debian-11-r22"
  - name: federated-kafka-ml-backend
    newName: host.docker.internal:50000/federated_backend
    newTag: latest
  - name: federated-kafka-ml-data_control_logger
    newName: host.docker.internal:50000/federated_data_control_logger
    newTag: latest
  - name: federated-kafka-ml-model_control_logger
    newName: host.docker.internal:50000/federated_model_control_logger
    newTag: latest
    